packages:
  - apps/*
  - packages/*
  - tooling/*

catalog:
  "@types/node": ^22.8.7
  commonality: ^0.2.63
  commonality-checks-recommended: ^0.0.40
  next: 15.0.3-canary.5
  react: 0.0.0-experimental-603e6108-20241029
  react-dom: 0.0.0-experimental-603e6108-20241029
  "@types/react": npm:types-react@19.0.0-rc.1
  "@types/react-dom": npm:types-react-dom@19.0.0-rc.1
  typescript: ^5.6.3
